
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'END EPSILON LETTER LPAR PLUS RPAR SEMI STARbegin : re SEMIre : termre : re PLUS termterm : factorterm : term factorfactor : nigglefactor : factor STARniggle : LETTERniggle : EPSILONniggle : LPAR re RPARniggle : END'
    
_lr_action_items = {'LETTER':([0,3,4,5,6,7,8,9,11,12,13,15,16,],[6,6,-4,-6,-8,-9,6,-11,6,-5,-7,6,-10,]),'EPSILON':([0,3,4,5,6,7,8,9,11,12,13,15,16,],[7,7,-4,-6,-8,-9,7,-11,7,-5,-7,7,-10,]),'LPAR':([0,3,4,5,6,7,8,9,11,12,13,15,16,],[8,8,-4,-6,-8,-9,8,-11,8,-5,-7,8,-10,]),'END':([0,3,4,5,6,7,8,9,11,12,13,15,16,],[9,9,-4,-6,-8,-9,9,-11,9,-5,-7,9,-10,]),'$end':([1,10,],[0,-1,]),'SEMI':([2,3,4,5,6,7,9,12,13,15,16,],[10,-2,-4,-6,-8,-9,-11,-5,-7,-3,-10,]),'PLUS':([2,3,4,5,6,7,9,12,13,14,15,16,],[11,-2,-4,-6,-8,-9,-11,-5,-7,11,-3,-10,]),'RPAR':([3,4,5,6,7,9,12,13,14,15,16,],[-2,-4,-6,-8,-9,-11,-5,-7,16,-3,-10,]),'STAR':([4,5,6,7,9,12,13,16,],[13,-6,-8,-9,-11,13,-7,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'begin':([0,],[1,]),'re':([0,8,],[2,14,]),'term':([0,8,11,],[3,3,15,]),'factor':([0,3,8,11,15,],[4,12,4,4,12,]),'niggle':([0,3,8,11,15,],[5,5,5,5,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> begin","S'",1,None,None,None),
  ('begin -> re SEMI','begin',2,'p_begin_1','REParser.py',14),
  ('re -> term','re',1,'p_re_1','REParser.py',19),
  ('re -> re PLUS term','re',3,'p_re_2','REParser.py',23),
  ('term -> factor','term',1,'p_term_1','REParser.py',38),
  ('term -> term factor','term',2,'p_term_2','REParser.py',42),
  ('factor -> niggle','factor',1,'p_factor_1','REParser.py',62),
  ('factor -> factor STAR','factor',2,'p_factor_2','REParser.py',66),
  ('niggle -> LETTER','niggle',1,'p_niggle_1','REParser.py',80),
  ('niggle -> EPSILON','niggle',1,'p_niggle_2','REParser.py',97),
  ('niggle -> LPAR re RPAR','niggle',3,'p_niggle_3','REParser.py',107),
  ('niggle -> END','niggle',1,'p_niggle_4','REParser.py',111),
]
